#!/bin/bash

echo "=== Nicole Adams Portfolio - GitHub Setup ==="
echo ""
echo "Run these commands one by one in the Replit Shell:"
echo ""
echo "1. Set up your Git identity (replace with your info):"
echo "   git config user.name \"Your Name\""
echo "   git config user.email \"your.email@example.com\""
echo ""
echo "2. Add your repository as remote:"
echo "   git remote add origin https://github.com/ChrisMacman2512/MC-Nicole.git"
echo ""
echo "3. Add all files to git:"
echo "   git add ."
echo ""
echo "4. Create initial commit:"
echo "   git commit -m \"Initial commit - Nicole Adams professional portfolio\""
echo ""
echo "5. Push to GitHub (you'll be prompted for authentication):"
echo "   git push -u origin main"
echo ""
echo "If you get authentication errors, you may need to:"
echo "- Use a Personal Access Token instead of password"
echo "- Set up SSH keys in your GitHub account"
echo ""
echo "Alternative: Use Replit's built-in Git integration:"
echo "- Go to the 'Version Control' tab in Replit"
echo "- Connect your GitHub account"
echo "- Push directly from the interface"